// <auto-generated />
using System;
using DesignDatabaseHotel.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_CRUD_Hotel.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20201216033245_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DesignDatabaseHotel.Model.BookingStatus", b =>
                {
                    b.Property<Guid>("BookingStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingStatusID");

                    b.ToTable("bookingStatuses");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Bookings", b =>
                {
                    b.Property<Guid>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReservationAgentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomCount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingID");

                    b.HasIndex("BookingStatusID");

                    b.HasIndex("GuestID");

                    b.HasIndex("HotelID");

                    b.HasIndex("ReservationAgentID");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Guests", b =>
                {
                    b.Property<Guid>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellularNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCOde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eMailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GuestID");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Hotels", b =>
                {
                    b.Property<Guid>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyeMailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Main")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Motto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TooIIFreeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCOde")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelID");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.PaymentStatus", b =>
                {
                    b.Property<Guid>("PaymentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentTypesPaymentTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentStatusID");

                    b.HasIndex("PaymentTypesPaymentTypeID");

                    b.ToTable("paymentStatuses");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.PaymentTypes", b =>
                {
                    b.Property<Guid>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTypeID");

                    b.ToTable("paymentTypes");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Payments", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaymentStatsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentID");

                    b.HasIndex("PaymentStatusID");

                    b.HasIndex("PaymentTypeID");

                    b.HasIndex("RoomID");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Positions", b =>
                {
                    b.Property<Guid>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionID");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RateTypes", b =>
                {
                    b.Property<Guid>("RateTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateTypeID");

                    b.ToTable("rateTypes");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Rates", b =>
                {
                    b.Property<Guid>("RateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<Guid>("RateTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RateID");

                    b.HasIndex("RateTypeID");

                    b.HasIndex("RoomsID");

                    b.ToTable("rates");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.ReservationAgents", b =>
                {
                    b.Property<Guid>("ReservationAgentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellularNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCOde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eMailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationAgentID");

                    b.ToTable("reservationAgents");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RoomStatus", b =>
                {
                    b.Property<Guid>("RoomStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomsStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomStatusID");

                    b.ToTable("roomStatuses");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RoomTypes", b =>
                {
                    b.Property<Guid>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("roomTypes");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Rooms", b =>
                {
                    b.Property<Guid>("RoomsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HotelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomsID");

                    b.HasIndex("HotelID");

                    b.HasIndex("RoomStatusID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RoomsBooked", b =>
                {
                    b.Property<Guid>("RoomBookedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingsBookingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomBookedID");

                    b.HasIndex("BookingsBookingID");

                    b.HasIndex("RoomID");

                    b.ToTable("roomsBookeds");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Staff", b =>
                {
                    b.Property<Guid>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellularNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PositionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCOde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eMailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.HasIndex("PositionID");

                    b.ToTable("staffs");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.StaffRooms", b =>
                {
                    b.Property<Guid>("StaffRoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffRoomID");

                    b.HasIndex("RoomID");

                    b.HasIndex("StaffID");

                    b.ToTable("staffRooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Bookings", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.BookingStatus", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.Guests", "Guests")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.Hotels", "Hotels")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.ReservationAgents", "ReservationAgents")
                        .WithMany("Bookings")
                        .HasForeignKey("ReservationAgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Guests");

                    b.Navigation("Hotels");

                    b.Navigation("ReservationAgents");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.PaymentStatus", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.PaymentTypes", null)
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("PaymentTypesPaymentTypeID");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Payments", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusID");

                    b.HasOne("DesignDatabaseHotel.Model.PaymentTypes", "PaymentTypes")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.Rooms", "Rooms")
                        .WithMany("Payments")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentStatus");

                    b.Navigation("PaymentTypes");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Rates", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.RateTypes", "RateTypes")
                        .WithMany("Rates")
                        .HasForeignKey("RateTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.Rooms", null)
                        .WithMany("Rates")
                        .HasForeignKey("RoomsID");

                    b.Navigation("RateTypes");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Rooms", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.Hotels", "Hotels")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.RoomStatus", null)
                        .WithMany("Rooms")
                        .HasForeignKey("RoomStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.RoomTypes", "RoomTypes")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotels");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RoomsBooked", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.Bookings", "Bookings")
                        .WithMany("RoomsBookeds")
                        .HasForeignKey("BookingsBookingID");

                    b.HasOne("DesignDatabaseHotel.Model.Rooms", "Rooms")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Staff", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.Positions", "Positions")
                        .WithMany("Staffs")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.StaffRooms", b =>
                {
                    b.HasOne("DesignDatabaseHotel.Model.Rooms", "Rooms")
                        .WithMany("StaffRooms")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDatabaseHotel.Model.Staff", "Staff")
                        .WithMany("StaffRooms")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rooms");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Bookings", b =>
                {
                    b.Navigation("RoomsBookeds");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Guests", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Hotels", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.PaymentTypes", b =>
                {
                    b.Navigation("PaymentStatuses");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Positions", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RateTypes", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.ReservationAgents", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RoomStatus", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.RoomTypes", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Rooms", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Rates");

                    b.Navigation("StaffRooms");
                });

            modelBuilder.Entity("DesignDatabaseHotel.Model.Staff", b =>
                {
                    b.Navigation("StaffRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
